### ISSUE TITLE
Inherit iconSets

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopware/docs#1030]
How to inherit iconSets? It is not mentioned within guides/plugins/themes/theme-inheritance-configuration.md

**Comment by Isengo1989** [comment]
@Nico-Schaefer-2111 what is your goal ?

Afaik the iconSets are passed along when using theme inheritance.

**Comment by Nico-Schaefer-2111** [comment]
@Isengo1989 

I tried the following setup on SW 6.4.20.2: 

* Create a main theme with iconSets 
* Create child themes with mostly the same stylings which are also using the IconSet. But within the child theme, the icons where not found by shopware, because they are not defined in the theme.json. 

I also tried to put the icons within the `<YourPlugin>/src/Resources/app/storefront/dist/assets/icon/<pack-name>` directory, like its mentioned on [Documentation](https://developer.shopware.com/docs/v/6.4/guides/plugins/plugins/storefront/add-icons) 
But that didn't worked at all, not even in the main theme!

**Comment by Isengo1989** [comment]
Since there is no response for 2 weeks I will close the issue as it seems it got resolved by the comment / is not needed anymore.
