### ISSUE TITLE
Was plugin description removed from composer.json?

### ISSUE THREAD

**Issue by Kudze** [shopware/docs#1097]
Hey, I'm referencing newest Shopware 6 version 6.5.4.1.

In past there was ability for plugins to define short description inside `composer.json` file, which was rendered in Extensions administration page. Now I have noticed that after defining the description inside `composer.json` file it would not render in the administration panel. (I have also opened some admin panel of existing 6.5 store and noticed that there are no descriptions for the plugins) The docs for 6.5 version are still stating that the description can be defined, as seen in the screenshot below:

![image](https://github.com/shopware/docs/assets/14080617/f777418c-cdef-4a55-8e29-d24e746eec57)
(Source: https://developer.shopware.com/docs/guides/plugins/plugins/plugin-base-guide)

The Q is is this a bug or intended feature?

In the case that it is intended feature docs have to be updated. I could create PR, where I would remove the description from the document. But before creating PR wanted to ask if this change was intended or not?

**Comment by Isengo1989** [comment]
@fabianhueske seems like the description block was removed at some point. Could you check if it was on purpose or by mistake so we might adjust the docs.

```
{% block sw_extension_card_base_info_description %}
        <section
            class="sw-extension-card-base__info-description"
            :title="description"
        >
            {{ description }}
        </section>
        {% endblock %}
```

**Comment by fschmtt** [comment]
Good morning,

we have intentionally removed this block from the template. The reason for this was mainly because only very few words of the description would be displayed in the current design of the "My extensions" listing. The space was simply too little to display especially long descriptions, so we figured this does not benefit the user and thus removed it.

But please keep maintaining the description as before, we might display the description again once we re-design the "My extensions" listing in the future.

I hope this answers your questions 😄

**Comment by Isengo1989** [comment]
@fschmtt thanks for the feedback. I noticed a tooltip that would show the full description with a native tooltip in 6.4.x - checking the changelog showed it was added in 6.4.18.0 

https://github.com/shopware/platform/blob/trunk/changelog/release-6-4-18-0/2022-10-12-show-extension-description-on-hover.md

**Comment by Kudze** [comment]
@Isengo1989 Okay, understood. Then yea everything looks alright. 

> as far as I see in the docs it does not describe that it is shown in the listing

Only that the default value inside example composer.json states this: "Description in the Administration for this plugin". Could be potentially misleading, but other than that I think you're right.
