### ISSUE TITLE
Add to EntityExtension page:

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopware/docs#1107]
Hey, 

Since i had problems in my current plugin with writing entity extension data from the administration (because i couldn't find how to do it the correct way):

Could you please add a short section below [EntityExtension | Writing into the new field](https://developer.shopware.com/docs/v/6.4/guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities#writing-into-the-new-field) 

which covers the writing process from the administration?

Kind regards

**Comment by sushmangupta** [comment]
Hi @Nico-Schaefer-2111 ,

**Comment by sushmangupta** [comment]
Hi @Nico-Schaefer-2111 ,
This guide on [Writing Operations](https://developer.shopware.com/docs/v6.4/guides/plugins/plugins/framework/data-handling/writing-data.html) has details on how to write data with examples. 
Are you looking for something specific?

**Comment by Nico-Schaefer-2111** [comment]
@sushmangupta thanks for your reply 

yes, I just tried to write data for an EntityExtension via administration, but that didn't work as expected. 
It has more todo with this doc article: [Using data handling | set a many to one](https://developer.shopware.com/docs/v6.4/guides/plugins/plugins/administration/using-data-handling.html#set-a-manytoone)

Here is the Problem i had with it:

normally you can save data to associated tables the way that you mentioned (within an array of the main object). 
Let's say i extended the ProductEntity with a OneToOneAssociation to a new custom Entity `ExampleExtensionEntity`. So i tried the following steps to create and save my customEntity (from the EntityExtension):

- I created the Object of my custom Entity (ExtensionEntity) with the appropriate repository e.g.: `exampleExtension = this.repositoryFactory.create('example_extension_entity').create(Shopware.Context.api)`
-  then I set my Object to the extended Object with the corresponding attribute. e.g. `this.product.exampleExtension = [exampleExtension]`
- then I tried to save all together: `this.productRepository.save(this.product, Shopware.Context.api)`

But when I look at the database table of my ExampleExtensionEntity there is no data saved at all and the save-command didn't even output any error.

So i want to know how to write extension

**Comment by Isengo1989** [comment]
@Nico-Schaefer-2111 can you get in contact with me via [Slack](https://shopwarecommunity.slack.com/team/U01AMM2F4S2)?

**Comment by Nico-Schaefer-2111** [comment]
@Isengo1989 Would like to, but I don't have the example prepared and can't really remember how to reproduce. So I also can't help to improve the docs at this point.

**Comment by Isengo1989** [comment]
@Nico-Schaefer-2111 a too bad, thought there might still be a private repo left to test it. You might want to try this approach if there is a chance:

`this.product.extensions.exampleExtension = this.repositoryFactory.create('example_extension_entity').create(Shopware.Context.api)`

So, the assignment to the product is missing the **extensions** part. I will test it, but might take some time. If so, we will fix the docs.

Here is an example: https://github.com/shopware/SwagPayPal/blob/trunk/src/Resources/app/administration/src/module/swag-paypal-pos/page/wizard/swag-paypal-pos-wizard/index.js#L297

Thanks to @mstegmeyer for the hint

**Comment by Isengo1989** [comment]
The following PR will add sufficient info about entity extension handling in the future

https://github.com/shopware/docs/pull/1317
