### ISSUE TITLE
Guide "Add custom flow Action" not working for Shopware 6.5.0.0+

### ISSUE THREAD

**Issue by alexeiffel** [shopware/docs#1216]
I think the guide was very poorly updated for Shopware 6.5.0.0+.
https://developer.shopware.com/docs/guides/plugins/plugins/framework/flow/add-flow-builder-action.html

The source code for CreateTagAction.php contains a variable `$baseEvent` that isn't even initialized but used in tag creation. The tag is showing up - but not under Customers section like shown. It also has the text "Unknown action".

When I create a `main.js` and `snippet/en_GB.json` like shown in section "Add custom action in Administration" the tag will still show up as "Unknown action" under Tags section.

**Comment by Isengo1989** [comment]
@nguyenky could you already take a look at this or should I create a ticket in Jira on the matter? :wave:

**Comment by sushmangupta** [comment]
WIP : https://github.com/shopware/docs/pull/1245

**Comment by sushmangupta** [comment]
@alexeiffel , the guide for  "Add custom flow Action" is updated. Hence closing this issue. Should you have any related queries further please feel free to open a new ticket.
