### ISSUE TITLE
Documentation for adding a custom Storefront controller (the service definition) seems worng 

### ISSUE THREAD

**Issue by AndreasA** [shopware/docs#1221]
According to https://github.com/shopware/docs/blob/main/guides/plugins/plugins/storefront/add-custom-controller.md#servicesxml-example

one should use 

```xml
 <call method="setContainer">
                <argument type="service" id="service_container"/>
            </call>
```

However, that will inject the service container and not the subscriber. As I discussed in the Symfony docu regarding how a controller is supposed to be instantiated without autowiring https://github.com/symfony/symfony-docs/pull/18841

what seems to work correctly is using `@Psr\Container\ContainerInterface` and the tags: `controller.service_arguments` and `container.service_subscriber` in which case `public="true"` can also be removed.

Furthermore, I think you should also mention the autowire, autoconfigure possibility here as it is way easier to use, even if Symfony usually recommends using the full definition in bundles https://symfony.com/doc/current/service_container/autowiring.html#public-and-reusable-bundles with Shopware the most relevant things for the controller are definitely available. and any other services are their own.

Furthermore, using a service subscriber here will allow you to remove the setTwig method as twig is part of the service locator.

**Comment by AndreasA** [comment]
also added the issue https://github.com/shopware/shopware/issues/3462 in the Shopware repo as it is done wrong in the shopware code as well, actually.

**Comment by Isengo1989** [comment]
Since this topic is dependent on the changes in the core we will close this issue for now. As soon as we go for the mentioned solution, the docs will be updated as well to keep the two aligned.
