### ISSUE TITLE
seo route option - mentioned and used in core but what does it actually do? still used?

### ISSUE THREAD

**Issue by AndreasA** [shopware/docs#1222]
The documentation mentions the seo option for the route attribute/annotation here https://developer.shopware.com/docs/resources/references/adr/2021-08-10-storefront-coding-standards.html#routes-annotations

However, it does not really explain what the difference is if it is used or if it is not used. Originally I thought it might be related to SEO URL generation but I could not find anything in the code and the documentation regarding custom seo urls does not mention it either https://developer.shopware.com/docs/guides/plugins/plugins/content/seo/add-custom-seo-url.html#add-custom-seo-urls

is it actually still relevant? if not, please remove it from the used controllers in the core and the documentation as it is somehow confusing.

**Comment by Isengo1989** [comment]
@keulinho as far as I can see this is used quite common in our controllers (frontend.wishlist.product.list etc.) - I did not find the code part where it is used. Does it prevent the route to be added to the seo_url table and/or the exposure to the sitemap?

**Comment by Isengo1989** [comment]
Since there is no need for documentation for now, this issue will be closed. Thanks for bringing it to our attention @AndreasA - as soon as it will be used / re-introduced we will cover it in the docs :+1:
