### ISSUE TITLE
documentation sometimes uses attributes, sometimes annotations - should probably only use attributes now

### ISSUE THREAD

**Issue by AndreasA** [shopware/docs#1224]
I noticed upon browsing the documentation that although it mostly now uses attributes, some still mention annotations like https://developer.shopware.com/docs/guides/plugins/plugins/content/seo/add-custom-seo-url.html#example-controller

**Comment by Isengo1989** [comment]
@AndreasA thank you for the hint :+1: 

@shyim I saw you applied the changes from annotations to attributes with rector rules. Is this already rolled out for the whole project? If so we would apply it to >= 6.5

**Comment by shyim** [comment]
we don't have any annotations anymore in 6.6. we don't support annotations even anymore

**Comment by Isengo1989** [comment]
Closed with https://github.com/shopware/docs/pull/1238
