### ISSUE TITLE
twig custom function documentation - naming convention

### ISSUE THREAD

**Issue by AndreasA** [shopware/docs#1225]
Hi,

I just noticed that on the "Add Custom Twig Functions" you use camelcase for the function names: https://developer.shopware.com/docs/guides/plugins/plugins/storefront/add-custom-twig-function.html 

however, usually twig filters/functions are in snake case (same with template names etc.), see also https://twig.symfony.com/doc/3.x/

furthermore, as multiple plugins add twig functions it might be a good idea to add a vendor specific prefix to the function name as well.

**Comment by AndreasA** [comment]
don't forget the vendor prefix in the docu regarding custom function. similar to other things it would be good to avoid clashes with other vendors. similar to entities etc.

**Comment by ssltg** [comment]
Thanks for the hint. I added that to the Issue description 👍

**Comment by ssltg** [comment]
For me its ok, we have the Issue to cover this further 👍
