### ISSUE TITLE
Missing docs: Get active theme id from sales channel entity

### ISSUE THREAD

**Issue by carstenjaksch** [shopware/docs#1418]
Let's face it: The docs are very incomplete. I am new to Shopware 6 and as a new user, I am dependend on good documentation.

Instead of asking multiple AIs, social media and forum communities, searching hundreds of Google results, the Shopware source code itself or annoy the 1st level support; I want to do something about the current situation. All these sources of information are mostly outdated or give utterly wrong answers to simple questions. A new user shouldn't need turning the internet upside down only to find some little information. All a new user needs, should be available in the official docs.

For every missing information, I will create an issue and hopefully, the docs can improve upon that. For the sake of new users like me, that may find Shopware 6 more welcoming in the future.

---

So I find myself in the situation where I need the active theme id of a sales channel. Let's say, I have a custom Twig function, that expects `SalesChannelEntity` as a parameter.

How do I get the active theme id for that `SalesChannelEntity`?

I am unsure where this information could fit in the current docs hierarchy. Maybe introduce a new "cookbook" area, where all real-life scenarios are handled. Some other CMSs out there have such a category and it is amazing.

Something like that:

```
Cookbook
- Entities
  - SalesChannel
    - Theme
      - Get active theme ID by sales channel
      - Get theme config by active theme id
```

**Comment by carstenjaksch** [comment]
After a long long search, I found one occurrence where Shopware does the same in an older version.

This is what I got and it works:

```php
  public function themeConfig(string $salesChannelId, Context $context)
  {
      $criteria = new Criteria([$salesChannelId]);
      $criteria->addAssociation('themes');

      $salesChannel = $this->salesChannelRepository->search($criteria, $context)->first();
      // Until here I knew how to use repositories.
      $theme = $salesChannel->getExtensionOfType('themes', ThemeCollection::class)->first(); // Never seen anything like that.

      return $this->themeService->getThemeConfiguration($theme->getId(), false, $context);
  }
```

It NEEDS to be documented somewhere!

**Comment by aragon999** [comment]
Not sure if this helps, but one issue here is, that the storefront package (where the theme stuff is located), is only an (optional) extension to the core package.

Therefore the theme is only added in the extension, to the sales channel, see here: https://github.com/shopware/shopware/blob/trunk/src/Storefront/Theme/Extension/SalesChannelExtension.php
Which is why you need to access it in the extensions of the of the found sales channel.

But I think I would reverse it, and not use the `sales_channel.repository`, but rather use the `theme.repository` and create a criteria which finds the theme, which has been assigned to the sales channel.

**Comment by carstenjaksch** [comment]
Thanks for your reply @aragon999.

This is why we need proper docs. Not only to show how to do things, but to discuss the topic deeply, show different ways of doing the desired thing and point to the recommended way.

And, last but not least, link to **all** related topics in the process.

That makes great documentation.

Instead, I talked to ChatGPT and the "copilot" of the Shopware docs, posted on Facebook, in the forum and slack, searched Google up and down ... Only to get outdated, not helpful and half-baked answers to a topic that should be handled in the official docs.

This is not the only topic I stumble over. This happens with EVERY thing I have to adjust in Shopware. Every documentation tells me only a bit of the puzzle or is simply not available. Sorry for my frustration, but I am exhausted to do all of that every time.

In this case, a reference of repositories would have helped me dramatically. Tell me what repositories are, which methods are available, what filters and associations are (and what they offer), etc.

I sincerely hope that will get better in the future.

**Comment by sushmangupta** [comment]
Hi @carstenjaksch ,
Thank you for reaching out. I wanted to inform you that our documentation is quite extensive, with most concepts well-covered in the guides section. However, it can be challenging to address every specific case. The good news is that Shopware is open-source, so you have the opportunity to contribute by creating pull requests. We encourage you to suggest and introduce new topics; we will consider adding them as needed. 👍

**Comment by carstenjaksch** [comment]
@sushmangupta Thank you for the answer.

I know that a good documentation is hard and therefore I wanted to try to do something about the current state.

Thus I created this issue to **suggest and introduce new topics**. I apologize for my outburst of emotions, but seeing this closed without any linked PR to really do something about the knowledge gap makes me even more unhappy than I already am.

Since I didn't create Shopware, I am unable to provide a PR for something I don't know. That's what this ticket is for: So that you are aware of the missing topic, create it and new developers are a little less stuck in the future.

I wanted to create more issues for things that are missing in the docs. But seeing this makes me think no one cares.
