### ISSUE TITLE
don't generate a 404 from Shopware for missing images

### ISSUE THREAD

**Issue by jonashrem** [shopware/docs#1461]
### PHP Version

/

### Shopware Version

6.6

### Affected area / extension

Platform(Default)

### Expected behaviour

On a missing media file in media or themes folder, shopware should not be instancieted at all

### Actual behaviour

At the moment, for every request resulting in a 404 from the web server, the Shopware index.php is called by .htaccess or nginx configuration.

This can create a negative performance impact, when clients try to access non-existing files like missing images or ico files.

For performance reasons, I suggest adding an option, to remove the media fallback completely ( in the installer for example )

### How to reproduce

call a  non existent media file ( you'll see a 404 Shopware page )

**Comment by jonashrem** [comment]
NGINX: https://github.com/shopware/docs/pull/1480

**Comment by jonashrem** [comment]
Apache: [#4730](https://github.com/shopware/shopware/pull/4730)

**Comment by Isengo1989** [comment]
@jonashrem, Since the topic has been brought to the product team's attention, I will close this issue. The PR in docs was merged, and I reached out to the maintainer of the flex repo for the current status.

Thx for your patience and PRs! :raised_hands:
