### ISSUE TITLE
Non-working example in: Adding complex data to existing entities

### ISSUE THREAD

**Issue by flytomek** [shopware/docs#1463]
I was following the example in the [documentation](https://developer.shopware.com/docs/v6.7/guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities.html) and durning execution of [migration](https://developer.shopware.com/docs/v6.7/guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities.html#adding-the-new-database-table), I got the following error:

`Failed to add the foreign key constraint. Missing unique key for constraint 'fk.swag_example_extension.product_id' in the referenced table 'product'`

I took closer look at the `product` table and realized, that the primary key of this table is not `id`, but `id, version id`.

So to make the documentation example working I had to do the following things:

1. Add additional column in the migration SQL:
```
`product_version_id` BINARY(16) NOT NULL,
```
2. Modify foreign key in the migration SQL:
```
CONSTRAINT `fk.swag_example_extension.product_id` FOREIGN KEY (`product_id`, `product_version_id`) REFERENCES `product` (`id`, `version_id`) ON DELETE CASCADE ON UPDATE CASCADE 
```
3. Add additional field in the entity definition class:
```
new ReferenceVersionField(ProductDefinition::class, "product_version_id"),
```

**Comment by Isengo1989** [comment]
@flytomek thx for creating the issue. I was following along the post in slack (recognizable with the :eye: ) - but appreciated anyways :+1: 

Currently verifying the change and thinking about a solution that is not being confused with entities that do not need the version_id.

Keep you posted here :wave:

**Comment by Isengo1989** [comment]
Closed - PR was opened -> https://github.com/shopware/docs/pull/1473
