### ISSUE TITLE
Add #[IsFlowEventAware] when defining a new Aware interface

### ISSUE THREAD

**Issue by applifaction** [shopware/docs#1492]
`#[IsFlowEventAware]` should be added in the code sample for defining a new "Aware" interface: 

See "### Create new Aware interface" in https://github.com/shopware/docs/blob/main/guides/plugins/plugins/framework/flow/add-flow-builder-action.md?plain=1

```php
// <plugin root>/src/Core/Framework/Event/TagAware.php
<?php declare(strict_types=1);
namespace Swag\ExamplePlugin\Core\Framework\Event;
use Shopware\Core\Framework\Event\FlowEventAware;

#[IsFlowEventAware]
interface TagAware extends FlowEventAware
{
    ...

    public const TAG = 'tag';

    public const TAG_ID = 'tagId';

    public function getTag();

    ...
}
```

**Comment by Isengo1989** [comment]
@applifaction what is meant by "in the code sample for defining a new "Aware" interface" - can you link the existing part in docs where this should be added?

**Comment by applifaction** [comment]
Interfaces which extend FlowEventAware like Tag**Aware**

**Comment by Isengo1989** [comment]
Ok, got it, thx for feedback.

**Comment by Isengo1989** [comment]
https://github.com/shopware/docs/pull/1617
