### ISSUE TITLE
Add permalink (redirect) for stable version

### ISSUE THREAD

**Issue by RafaelKr** [shopware/docs#1520]
I just wanted to add a comment to my configuration pointing to a specific part of the Shopware developer documentation.

As the documentation is a living document I'd like to be able to point to the documentation of the current release. Specifically I would like to point to https://developer.shopware.com/docs/v6.6/resources/references/config-reference/server/nginx.html but it throws a 404.

It works if I do
https://developer.shopware.com/docs/v6.4/resources/references/config-reference/server/nginx.html
https://developer.shopware.com/docs/v6.5/resources/references/config-reference/server/nginx.html
https://developer.shopware.com/docs/v6.7/resources/references/config-reference/server/nginx.html

but not for the current stable release.

I would suggest to implement a redirect for the link including the stable version.

**Comment by bojanrajh** [comment]
Hey, thanks for the feedback!

Yeah, it makes sense to future-proof the link, even if it doesn't exist at the moment (but we know it will). :) Here's the [change](https://github.com/shopware/developer-portal/pull/403) and a [redirect](https://developer.shopware.com/docs/v6.6/resources/references/config-reference/server/nginx.html).

**Comment by RafaelKr** [comment]
Awesome, thanks for the fast implementation!

**Comment by RafaelKr** [comment]
I just noticed it's a 301 redirect. Wouldn't make a 302 redirect more sense, as it's temporary?
