### ISSUE TITLE
Missing images?

### ISSUE THREAD

**Issue by melroy89** [shopware/docs#1527]
I don't see any diagrams or images on the documentation page, like: https://developer.shopware.com/docs/resources/references/adr/2021-10-01-payment-flow.html??

I believe something goes wrong. Like either the asset is removed or not generated correctly. Or invalid png: https://developer.shopware.com/assets/asynchronous-payment.BzwXwsjL.png

**Comment by Isengo1989** [comment]
Thx @melroy89 for informing us! Should be fixed with the next deployment.

If you need the images right aways pls check our main repo -> https://github.com/shopware/shopware/tree/trunk/adr
