### ISSUE TITLE
`.editorconfig` missing

### ISSUE THREAD

**Issue by jrson83** [shopware/docs#1562]
I noticed because there is no `.editorconfig`, the line spacing within the Markdown files is not consistent, as some are saved with 2 and some with 4. As I like to fix the code block issues with xml language and find it hard to work with an unconsistent file formatting, I like to create a PR to fix the issue, if welcome.

**Comment by Isengo1989** [comment]
@jrson83 we are using markdown lint for that (https://github.com/shopware/docs/blob/main/markdown-style-config.yml)

Maybe that rule does what you are looking for -> https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md046---code-block-style

What is the issue you were mentioning?

**Comment by jrson83** [comment]
Thanks for reply. But I think this has nothing to do with the linter. If you look at the .md files in the IDE without forced `.editorconfig`, you can see that they were created with inconsistent or undefined line spacing.

For the other issue please see here: https://github.com/shopware/docs/pull/1557/files/1daa8d9de365dc694f99e302f10aadf0c24398ad#r1841759820

**Comment by jrson83** [comment]
@mitelg 2 or 4?

**Comment by Isengo1989** [comment]
Hey @jrson83 the [PR](https://github.com/shopware/docs/pull/1585) was merged - feel free to create one based on the space indent of 2 with an .editorconfig as talked about in the other issue 👋

**Comment by Isengo1989** [comment]
Closing the issue, let's continue on the PR 🙂
