### ISSUE TITLE
Vitepress CSS layout issues

### ISSUE THREAD

**Issue by jrson83** [shopware/docs#1599]
There are currently two issues with the docs vitepress css layout:

1. The hamburger button breaks out the layout on mobile devices:

![Image](https://github.com/user-attachments/assets/0663a1d9-5dd0-48a9-8fe3-b969e968c207)

2. There is an issue with the fade out sticky navbar, causing a layout shift when scrolling down a page, everytime the navbar fades in and becomes sticky again:

![Image](https://github.com/user-attachments/assets/2ea0250f-44cc-4cc6-98b7-1a82ffb66501)

Is it possible to get access to the vitepress to fix those issues?
Else it would be awesome if somecone could take care of this.

**Comment by Isengo1989** [comment]
@jrson83 thx for noticing 👋 

You can find the repos here -> https://github.com/shopware/developer-portal and https://github.com/shopware/developer-documentation-vitepress

If you need help setting it up, let me know. The portal basically imports multiple docs repos.

@bojanrajh fyi

**Comment by jrson83** [comment]
@Isengo1989 awesome, I gonna look into it.

**Comment by jrson83** [comment]
@bojanrajh the issue only occours on real mobile devices, I guess cause of the mediaqueries.
The layout shift does not occour when I use desktop chrome or firefox with emulation for mobile devices enabled.

Please try use a real mobile device with latest chrome. I have a Samsung S20 Plus.

**Comment by jrson83** [comment]
@bojanrajh I see the issue with layout shift has also been resolved with your linked commit.
Should all be resolved great job, thanks!

**Comment by Isengo1989** [comment]
Perfect. Thx for the fix @bojanrajh and for testing @jrson83 

Closed
