### ISSUE TITLE
[very small issue] Diagram transaction statemachine, cancelled block should have a line to end symbol?

### ISSUE THREAD

**Issue by JelteV** [shopware/docs#250]
On https://github.com/shopware/docs/blob/master/concepts/commerce/checkout-concept/orders.md in the order transaction state machine diagram (https://github.com/shopware/docs/blob/master/.gitbook/assets/order-payment-state-machine.png) I think there should be a line from the cancelled block to the UML end symbol.

**Comment by PaddyS** [comment]
@elkmod Do you know where the UMLs to those images are stored?

**Comment by PaddyS** [comment]
Hey @JelteV,
thank you for the issue!

I do get what you're trying to say and technically you're correct here.
Technically there should be several final states, e.g. "paid", "refunded" etc.

"Refunded" and "Paid" happened to be close to the final state, so you could easily connect them. I think the "Cancelled" state is supposed to be a final state itself here.

Is that okay for you?

**Comment by JoshuaBehrens** [comment]
Do we still have the source plant uml files in this repo?

**Comment by PaddyS** [comment]
@JoshuaBehrens Sadly, no. Couldn't really figure out where it came from. 😱

**Comment by JoshuaBehrens** [comment]
@PaddyS here are some https://github.com/shopware/platform/tree/a702b403192743162808cc5213ff3748856993da/src/Docs/Resources/current/60-references-internals/10-core/10-erd/_puml maybe we can find some more old ones. Good thing you have no custom style so they are easy to re-create 😁

**Comment by PaddyS** [comment]
@JoshuaBehrens We had a look at those, but THAT one isn't there, sadly. :-(

**Comment by JoshuaBehrens** [comment]
😢
