### ISSUE TITLE
Adding custom rules example doesn't add them to dynamic group rules

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopware/docs#252]
I just tested the Custom rules Example and it doesn't seem like this example also adds the rule to dynamic product groups. So i think there is a difference between these two components, but i can't find a doc article about adding custom 'dynamic product group rules' or at least an article about the system behind them.

**Comment by PaddyS** [comment]
Thanks for reporting @Nico-Schaefer-2111, I will have a look at it. 🙏

**Comment by PaddyS** [comment]
Hey @Nico-Schaefer-2111, I just had a quick look at it:
It seems like only very basic rules are possible, such as "field X of entity X is 5".

In detail, the dynamic product groups only seem to consist of specifically allowed entities and their respective fields, so only very basic rules are possible.
You can find the list of available rules [here](https://github.com/shopware/platform/blob/trunk/src/Administration/Resources/app/administration/src/app/service/product-stream-condition.service.js#L18-L66).

The filters are saved in the database table `product_stream_filter`, which also only allows very basic conditions.

I guess you COULD create custom conditions here by also adjusting the `ProductStreamBuilder` PHP class, but that seems to be kinda hacky in total.
