### ISSUE TITLE
NGINX Template prevents xml feeds from loading

### ISSUE THREAD

**Issue by jr-timme** [shopware/docs#256]
The current [NGINX Template ](https://github.com/shopware/docs/blob/master/resources/references/config-reference/server/nginx.md)prevents XML Feeds from loading as NGINX tries to serve them as static files. In case of the XML Feeds however they are generated by PHP and therefore NGINX only produces a HTTP 404

The location block: `location ~* ^.+\.(?:css|cur|js|jpe?g|gif|ico|png|svg|webp|html|woff|woff2|xml)$ {` needs to either not include xml files or you could add a `try_files $uri /index.php$is_args$args;` to fallback to php in case a file is not found

**Comment by shyim** [comment]
Thanks! 😊

**Comment by PaddyS** [comment]
Hey @jr-timme,

thank you for reporting. 🎉 
As you might have noticed, @shyim already created a PR to fix it. :-)
