### ISSUE TITLE
How to call parent services methods when they are private?

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopware/docs#302]
The doc article describes how to decorate a service. But most of the services, which I want to edit, need to call private methods of the parent! 

I found a method to do this on stackoverflow (see the answer from "Jed Lynch", mentioning the ReflectionMethod Class): 

https://stackoverflow.com/questions/12603766/call-private-method-from-inherited-class

Please insert it to the doc or tell me how to do it otherwise.

**Comment by JoshuaBehrens** [comment]
As private methods are not part of the public API I'd never want to rely on a function that others don't expect will be used elsewhere. I suggest you to copy that method and add comments where the original source comes from and how to proceed on an update.

**Comment by PaddyS** [comment]
Hey @Nico-Schaefer-2111,

thank you for your issue and the underlying concerns.

Yet, private methods are not supposed to be used in any way and doing this with Reflection classes will work, but is rather considered 'hacky' and also slow in terms of performance.

If you **really** need to use a private method, you can either do what @JoshuaBehrens said or, if you think that it should have been public or protected in the first place, you can still [create a pull request](https://github.com/shopware/platform/pulls) to change this in our code.

Will this do the trick for you? :-)

**Comment by Nico-Schaefer-2111** [comment]
Thanks for the quick responses. 

Mhh i will think about a pull request, but in first place I will implement it like @JoshuaBehrens  recommended.
