### ISSUE TITLE
Custom-rules example not very representative

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopware/docs#306]
[guides/plugins/plugins/framework/rule/add-custom-rules.md](https://github.com/shopware/docs/blob/master/guides/plugins/plugins/framework/rule/add-custom-rules.md)

This example should show a basic usage of v-models, v-bind and v-on and how to store multiple condition values.

**Comment by Nico-Schaefer-2111** [comment]
After some problems i got the template and the component wired up correctly i think... 

But if i want to safe the condition with selected "zipCodeParts" value there is an error which tells me 

```
There are 1 error(s) while writing data.

1. [/0/conditions/0/children/0/children/0/value/zipCodeParts] The property "zipCodeParts" is not allowed.
```


Here my index.js: 

```
import template from './postal-code.html.twig';
import { Component } from 'src/core/shopware';

Component.extend('s1-postal-code', 'sw-condition-base', {
    template,

    computed: {

        selectValues() {
            return [
                {
                    label: 'beginnt mit',
                    value: true
                },
                {
                    label: 'beginnt nicht mit',
                    value: false
                }
            ];
        },

        options(){
            return [
                {
                    label: '01',
                    value: '01'
                },
                {
                    label: '02',
                    value: '02'
                }];
        },

        negator: {
            get() {
                this.ensureValueExist();
                if (this.condition.value.negator == null) {
                    this.condition.value.negator = false
                }

                return this.condition.value.negator;
            },
            set(negator) {
                this.ensureValueExist();
                this.condition.value = { ...this.condition.value, negator };
            }
        },

        zipCodeParts: {
            get() {
                this.ensureValueExist();
                if (this.condition.value.zipCodeParts == null) {
                    this.condition.value.zipCodeParts = [];
                }
                console.log(this.condition.value)
                return this.condition.value.zipCodeParts;
            },
            set(zipCodeParts) {
                console.log('zipCodeParts -> set()');
                console.log(zipCodeParts);
                console.log(this.condition.value);
                this.ensureValueExist();
                this.condition.value = { ...this.condition.value, zipCodeParts};
                console.log(this.condition.value);
            }
        }
    }
});
```

**Comment by PaddyS** [comment]
Hey @Nico-Schaefer-2111,

can you ellaborate a little bit on what exactly you're missing here?
`v-on` and `v-bind` are default vue directives and are in my opinion not really bound to custom rules.

However, I can think of having more examples, e.g.:
- Using a multi select
- Rules with an included search
- Rules with conditions (e.g. "Equals one of", "Is greater than", ...)

Did you mean any of those?

**Comment by Nico-Schaefer-2111** [comment]
Hey, 
sorry for being imprecise. 

> 
> * Using a multi select
> * Rules with an included search
> * Rules with conditions (e.g. "Equals one of", "Is greater than", ...)
> 

Yeah i meant exactly some of them, because when you don't have any experience with vueJS you don't know how it works exactly and how you can combine template and component. 

An example with a multi select would have been great help and either are rule in combination with conditions. :)

**Comment by PaddyS** [comment]
Just for your information: I've created an internal ticket for that. Unfortunately I can't give an ETA about it though.

**Comment by sushmangupta** [comment]
@Nico-Schaefer-2111 , thanks for raising your concern. Here is a ticket that would work on your request as we advance: https://shopware.atlassian.net/browse/DX-377
