### ISSUE TITLE
style color for sw_icons don't work

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopware/docs#336]
I am using shopware 6.4.1.0 and just tried to insert an shopware icon to my theme like mentioned in:

shopware/docs/guides/plugins/themes/add-icons.md

Therfore the code

`{% sw_icon 'shield' style {'color': 'white'} %}` 

is supposed to insert a white shield icon, but it is inserted with a grey color.

**Comment by sushmangupta** [comment]
@Nico-Schaefer-2111 , thanks for the hint. The info is now updated. Hence closing this issue. :)
