### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by elkmod** [shopware/docs#375]
In the old documentation we used to mention browser compatibilities of our components Storefront & Admin as such:

## Browser Compatibility Note:

**Administration**

All browsers in the latest version (Edge, (no IE), Chrome, Firefox, Safari, Opera)

**Storefront**

All browsers in the latest version and additionally IE 11

---

We should add that information to the respective concept page of the components Storefront, Admin & PWA.

@chrissor 
@htkassner 
@patzick

**Comment by JoshuaBehrens** [comment]
Storefront IE11 works? :O

**Comment by sushmangupta** [comment]
After discussion, closing this issue.
