### ISSUE TITLE
Docs for EntityExtensions with OneToOneAssociationFields and EntityExtension inheritance

### ISSUE THREAD

**Issue by sawden** [shopware/docs#410]
### Please describe the feature you would like to see implemented.

Would be nice to have official documentation and an example for OneToOneAssociationFields.

I tried to expand the product entity with a OneToOneAssociationField and came across countless questions and problems.

Problems I have encountered:
- If "autoload" is set to "true" in the product extension and my custom entity, shopware breaks totally and i get an HTTP-error 503 on most of the Endpoints. [Is this a Bug?](https://issues.shopware.com/issues/NEXT-11012).
- Inheritance does not seem to work properly if OneToOneAssociationFields are used to extend the product.

**Comment by rs-ubaldi** [comment]
On year opened and we have the same issues here !

**Comment by sawden** [comment]
> On year opened and we have the same issues here !

The bug with the inheritance in OneToOneAssociationFields was actually fixed about 4 weeks ago.
The 'autoload' issue still doesn't seem to be resolved, but you can load your entity manually in the storefront. 
Take a look at this article: https://webkul.com/blog/how-to-extend-the-entity-at-the-shopware/

**Comment by rs-ubaldi** [comment]
> OneToOneAssociationField

Hi sawden, thank you but I have already viewed this page and you dropped the OneToOneAssociationField in favor of a OneToManyAssociationField which does not work for us here

**Comment by sawden** [comment]
No you can still use OneToOneAssociationFields but due to the autoload bug you have to load the data manually with 'EventSubscriberInterface' as described in the article.

**Comment by rs-ubaldi** [comment]
> No you can still use OneToOneAssociationFields but due to the autoload bug you have to load the data manually with 'EventSubscriberInterface' as described in the article.

Thanks again, I have re-read the article and manage to have something working by seed inside the event subscriber.

**Comment by Isengo1989** [comment]
@sawden I added info about the recursion in the [PR](https://github.com/shopware/docs/pull/1028) and on Foreign Keys to make this topic complete.

Since the Issue is reported in platform, I will close the docs issue.

Thank you for the report :+1:
