### ISSUE TITLE
Missing "Edit page on Github"

### ISSUE THREAD

**Issue by Tschucki** [shopware/docs#422]
Has the button been completely removed or has it been moved somewhere else?
Because I can't find the button anymore.

**Comment by elkmod** [comment]
Thanks for bringing up the issue @Tschucki! It seems like the latest update of the service broke the synchronization as well as the "Edit page on GitHub" button. We are in contact with their support to fix the problem :)

**Comment by elkmod** [comment]
The button is back! 😍

![image](https://user-images.githubusercontent.com/7780750/144218616-88f0bbbe-d105-4403-a0c0-9fb23f5a0a65.png)
