### ISSUE TITLE
Probably missing docu only - Variants - Store API - How to filter to main variant or all variations and how to select a product based on selected options?

### ISSUE THREAD

**Issue by AndreasA** [shopware/docs#424]
**Description**  
This probably is already possible but in that case it is missing from the documentation.

**List route**
- How do you limit that API to main variants only?
- How do you limit that API to show only variants and exclude the main product.

If I understand this correctly the store api product listing response takes the `Storefront presentation` settings into account?

If so, this really should be documented. Also it shouldn't be called storefront presentation as it is also available in headless mode.

**Detail route**
It is nice that the route delivers the configurator settings and all options but how do you find the corresponding variants for that options? In storefront there is the route `frontend.detail.switch` but how do you do this easily with the store API? Sure I can do a search/list route call for this but somehow that does not seem like the best/easiest solution.

Maybe also just missing documentation.

**Comment by sushmangupta** [comment]
@AndreasA , Since this issue was transferred to the shopware/platform, closing the duplicate copy. 
Thanks for raising the issue.
Please feel free to reopen it if required. 👍
