### ISSUE TITLE
Add a way to reference custom assets in admin modules CSS

### ISSUE THREAD

**Issue by AlexBachmann** [shopware/docs#426]
**Description**  
Documentation exists on how to use custom assets in our admin modules:
https://developer.shopware.com/docs/guides/plugins/plugins/administration/using-assets#use-custom-assets-in-the-administration

However, this documentation only explains how to USE these assets using the `asset` filter in TWIG templates. 
If we want to reference custom fonts and other assets in our CSS files, we cannot use this filter.

This is a problem, because the path to these assets differs, whether or not you are using the webpack server in the dev environment (using `psh.phar administration:watch`) or you're using the prod environment.

**Comment by sushmangupta** [comment]
@AlexBachmann , Since this issue was transferred to the shopware/platform, closing the duplicate copy. 
Thanks for raising the issue.
Please feel free to reopen it if required. 👍
