### ISSUE TITLE
MainProduct cannot be a variant?

### ISSUE THREAD

**Issue by tinect** [shopware/docs#428]
**Description**  
We try to import some products via repository that gets stuck on variants.
We have many products differ in colours. One colour is the mainProduct containing `configuratorGroupConfig` and `configuratorSettings`.
The variants relating [ProductListingTest.php#L250](https://github.com/shopware/platform/blob/6.1/src/Core/Content/Test/Product/SalesChannel/ProductListingTest.php#L250) with options. These options in mainProduct are getting ignored.

While doing this, just the variants (with parentId) are displayed in storefront. In administration, we need to generate the missing color-variant, but this results in a new productNo - which is wrong.

Is this intended? I think, nobody wants to add pseudo-mainproducts :-)

**Possible Solution**  

**Additional context**

**Comment by sushmangupta** [comment]
Since this issue is transferred to the shopware/platform, closing the duplicate copy. 
Thanks for raising the issue.
Please feel free to reopen the issue if required. 👍
