### ISSUE TITLE
No documentation for the use of component props in config.xml

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopware/docs#442]
On the [this page](877939) is mentioned, that you can use any shopware component inside the plugin configuration. 

I tried to use the [ip-selection](https://component-library.shopware.com/components/sw-multi-tag-ip-select?q=enti), but it is not working, since it's [parent](https://component-library.shopware.com/components/sw-multi-tag-select) requires the property "value". 

Either it is not possible to pass properties from the xml to the vueJS-component or it is just not/bad documented since I didn't find it.

Best regards

**Comment by elkmod** [comment]
Hi Nico - could you please specify where it was stated that you can use any component inside the configuration? Unfortunately, the link you provided does not work.

We're happy to help out!

**Comment by Nico-Schaefer-2111** [comment]
Hello @elkmod 
Sorry, somehow the link got broken. I meant this one:

https://github.com/shopware/docs/blob/master/guides/plugins/plugins/plugin-fundamentals/add-plugin-configuration.md#advanced-custom-input-fields

**Comment by elkmod** [comment]
Thank you for providing us with the link @Nico-Schaefer-2111. The documentation mentions that "many" components can be  rendered, however not "any", as you pointed out in your example. Also, see the hint below saying

> Please Note: It is impossible to allow every component to the config.xml, due to their complexities. If you can't efficiently resolve your plugin's necessities with, it is probably better to create an own module instead. Therefore, Shopware supports the following components by default (also to be found in the ConfigValidator class).
