### ISSUE TITLE
Reading plugin configuration in administration

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopware/docs#443]
is there a way to read the plugin configuration inside of an administration component? 

I already found something to inject the 'systemConfigApiService', but all of my calls are responding with errors. 

So when there is a way please document it :)

**Comment by elkmod** [comment]
Hey @Nico-Schaefer-2111 - your approach sounds correct. However, if you're having troubles with the implementation, please refer to our Slack Channel. We will happily pick up on your suggestion to document this, but cannot give you any estimated date.
