### ISSUE TITLE
Searching the documents in Github is more helpful than on the actual page

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/docs#466]
![grafik](https://user-images.githubusercontent.com/1133593/148953701-40cbc428-d44b-4510-bb03-2ac054e4358f.png)
![grafik](https://user-images.githubusercontent.com/1133593/148953828-92ca96e2-a6eb-4ae5-8d0f-9ed16ba26bf2.png)

I was looking for the order of the indexing commands. I had a preview and immediately saw the infrastructure content preview in the Github search. On the actual documentation page the sidebar is quite stale and non-descriptive. It was the third hit I was looking for but how do I know that this order stays the same?

**Comment by elkmod** [comment]
Hi Joshua! We completely agree with you - we are not really pleased with the way our search results are displayed either.. We are discussing it with our frontend provider to see whether we can expect some improvements. Unfortunately this is not in our hands at the moment..

**Comment by JoshuaBehrens** [comment]
HI @elkmod thanks for taking that topic with you :) For now I will use the github search

**Comment by JoshuaBehrens** [comment]
@elkmod nice :) works pretty good

![image](https://user-images.githubusercontent.com/1133593/159305098-ad76fd18-5c9c-4542-bd2e-2847796172d5.png)
