### ISSUE TITLE
Document necessary step for testing in production template

### ISSUE THREAD

**Issue by svlauer** [shopware/docs#476]
[This section](https://developer.shopware.com/docs/guides/plugins/plugins/testing/php-unit#production-template) provides guidance on how configure/run unit tests for plugins when using the production template.

As far as I can see, the section is incomplete because it does not outline the necessary steps to ensure that the plugin to be tested is loaded in the testing environment - this becomes an issue in particular if the tests rely on services defined by the plugin (and perhaps in other circumstances).

In the production template, one has to create a custom bootstrap file, like so (modeled on the `TestBootstrap.php` file in core:
```php
<?php declare(strict_types=1);

namespace ...;

use Shopware\Core\TestBootstrapper;

(new TestBootstrapper())
    ->setPlatformEmbedded(false)
    ->addCallingPlugin()
    ->setForceInstallPlugins(true)
    ->bootstrap();
```
The important lines are the calls to ``addCallingPlugin()`` (ensuring that the plugin to be tested is active) and to ``setForceInstallPlugins()``(because otherwise,  the previous call is ignored if the test database exists already).

(In the development template, this is not necessary, since (I believe) `./psh.phar init-test-databases` ensures that the plugin to be tested is active in the test database).)

As it stands, following the steps in the referenced section will lead to a faulty testing environment (unless you happen to execute for the first time when the test database does not exist yet), so I really think this should be documented.

**Comment by wazka83** [comment]
Thank you. Documentation is misleading

**Comment by Isengo1989** [comment]
@svlauer thank you for the info. The new docs contain the mentioned options.
![2023-09-27_10-15](https://github.com/shopware/docs/assets/8600299/48051e7d-279a-4291-a03a-d55a1a285c51)
