### ISSUE TITLE
Custom admin shortcuts not working

### ISSUE THREAD

**Issue by Zerotask** [shopware/docs#494]
I followed the documentation for adding a shortcut here https://developer.shopware.com/docs/guides/plugins/plugins/administration/add-shortcuts
but this doesn't work. I'd assume to the console logs when pressing alt + s (windows), but nothing happens.
Is there something missing in the documentation? I tried other docs like replacing a text on the welcome screen which worked as expected.

I'm using Shopware 6.4.8.0 with an admin account

**Comment by seggewiss** [comment]
Tested according to documentation works as expected. See [here](https://github.com/seggewiss/shortcut-example) for example.

**Comment by Zerotask** [comment]
@seggewiss Thanks for taking the time and check my issue.

Your example works but you added way more code than the example shows. 
If I simply add the code from the documentation and add it to my main.js, so it gets loaded, it does not work.
You have to add a template and then add it to a specific page and then the shortcut only works on this page.
For an experienced developer this is maybe clear but not for me and some others.

My assumption was, that I simply add a shortcut as described in the documentation, add it to my main.js and then it simply works on every page in the administration.
Therefore the documentation should be extended to make it clear, that you have to do other steps.
