### ISSUE TITLE
Unclear documentation for read-only entity extension fields

### ISSUE THREAD

**Issue by dallyger** [shopware/docs#498]
I wanted to create an entity extension containing a "field without database" but got confused by the docs.
There are so many open questions and assumptions.

What are the field-types for? It seems to have no effect if I use a "BoolField", "StringField" or anything else.

What should I add as an extension? "Please note that its second parameter [...] has to be a struct" is too unspecific.

And what does the `customString`-value from the example do? Doesn't get used anywhere.

Also, the example doesn't add up it seems.

Here it gets defined as a StringField:
https://github.com/shopware/docs/blob/4258b15afa1fa83e3a8f1d8e3ad466580d33a33b/guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities.md?plain=1#L282

But later on, it gets assigned an ArrayStruct?
https://github.com/shopware/docs/blob/4258b15afa1fa83e3a8f1d8e3ad466580d33a33b/guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities.md?plain=1#L326

When I follow it, it works but is confusing as hell, when I look at the dump of the entity:

```
#extensions: array:1 [
    "custom_string" => Shopware\Core\Framework\Struct\ArrayEntity {[#2836]()
      #data: array:1 [
        "foo" => "bar"
      ]
      #_entityName: "array-entity"
      #_uniqueIdentifier: null
      #versionId: null
      #translated: []
      #createdAt: null
      #updatedAt: null
      #extensions: []
      -_entityName: null
    }
  ]
```

Here, `custom_string` is not the name of the field as expected, but of the extension? How can it be defined as a "StringField" but not return a string?

**Comment by dallyger** [comment]
Hi @PaddyS, can you help me here?
Sorry for contacting you directly, but getting ignored on every official channel is pretty frustrating, and you've added the example in the first place. So I didn't know who else to contact.

**Comment by sushmangupta** [comment]
@dallyger , thanks for raising this issue and sorry for the delayed response. 
We have internally created a [ticket ](https://shopware.atlassian.net/browse/DX-378) to address your concern. We shall be working on this going forward.

**Comment by Isengo1989** [comment]
@dallyger we removed the confusing part. Thank you for the hint :+1: 

https://github.com/shopware/docs/pull/1302
