### ISSUE TITLE
Bash examples contain ">" in front of command, resulting in overwriting the command

### ISSUE THREAD

**Issue by millsoft** [shopware/docs#509]
Hi, there is an issue with the bash examples, eg here:

https://developer.shopware.com/docs/guides/installation/docker

```bash
> ./psh.phar docker:start
```

The problem is that the `>` character in front of the command is also copied into clipboard if I click on the "copy code" button.
If I paste the command into terminal and execute it, the file `./psh.phar` will be overwritten with nothing. The file is simply empty and I need to redownload psh.phar and make it executable again.

Solution would be: remove the `>` in front of the command or make it unselectable via css / script.
I just found it in the docker docs part but there might be more of these `>` characters inside the docs.

**Comment by Christian-Rades** [comment]
Thanks for the suggestion; I agree it's annoying.
