### ISSUE TITLE
Inaccurate directory diagram for extended administration modules

### ISSUE THREAD

**Issue by hqcasanova** [shopware/docs#519]
In the section [_Creating your new component_](https://developer.shopware.com/docs/guides/plugins/plugins/administration/add-new-tab#creating-your-new-component) of the "_Add tab to existing module_" chapter, the following diagram is missing the second-level `src` folder under the `administration` root one:

```
administration
├── page
│   └── sw-product-detail
│       └── sw-product-detail
│           ├── index.js
│           └── sw-product-detail.html.twig
├── view
│   └── sw-product-detail-custom
└── main.js
```
This is in contrast with what's stated elsewhere in the same chapter. For example, within the [reminder box](https://developer.shopware.com/docs/guides/plugins/plugins/administration/add-new-tab#please-remember) towards the end of the "Prerequisites" section:
>The main entry point to customize the administration via plugin is the main.js file. It has to be placed into a <plugin root>/src/Resources/app/administration/src directory in order to be found by Shopware 6.

**Comment by sushmangupta** [comment]
@hqcasanova , sorry for the delayed response and thanks for raising this issue. It's now been updated :)
