### ISSUE TITLE
Deployment with Deployer

### ISSUE THREAD

**Issue by sawden** [shopware/docs#535]
The [Deployment with Deployer](https://developer.shopware.com/docs/guides/hosting/installation-updates/deployments/deployment-with-deployer) Docs page is outdated and do not work with the latest version of shopware.
The article should be updated or provided with a note that this is outdated and only works up to version 6.3.*

Shopware is awesome 🛒💙

**Comment by Isengo1989** [comment]
Hey @sawden - sorry for the long wait. Do you remember which part was not working for you in <= 6.3.*

I did use the guide for 6.4.18.* - so just making sure we do not recommend the wrong max. version.

**Comment by sawden** [comment]
Hi there,

Apologies, but it's been quite a while since I originally posted this issue and I can't provide detailed specifics about which parts were not working for me.

My workaround at the time was to use the Docker setup provided by @shyim, which you can find at this link: https://github.com/shyim/shopware. That solution worked well for me. 🙂

**Comment by Isengo1989** [comment]
@sawden thanks for the feedback! I will look into it with my colleague :wave:

**Comment by Isengo1989** [comment]
@sawden I updated the docs to work with the newest version :wave: 

https://github.com/shopware/docs/pull/1039
