### ISSUE TITLE
CMS Block storefront example is not helpful to understand the twig templating

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/docs#542]
https://developer.shopware.com/docs/guides/plugins/plugins/content/cms/add-cms-block

Pls improve

@niklaswolf
@Christian-Rades

**Comment by JoshuaBehrens** [comment]
@jissereitsma suggests to add a conclusion section to dive into some further topics

**Comment by niklaswolf** [comment]
Just to add a quick description what should be improved (already discussed with @Christian-Rades:
- currently the example used there is more like extending a already existing block, but in my view it should be an example of really creating a new one. The current how to could be kept but maybe more to show how to extend a new one
- more "linked" docs regarding the whole CMS extension topic: blocks, elements, data-resolvers, API-responses,...
- improved overview on how the whole system works and how the different elements belong and work together.

**Comment by sushmangupta** [comment]
As this ticket dates back quite a bit, it's worth noting that our documentation has undergone improvements over time. Consequently, we are closing this ticket. If you have specific additions or concerns, please don't hesitate to open a new ticket for further assistance.
