### ISSUE TITLE
MAMP Guide suggests to use php7.2

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/docs#551]
https://github.com/shopware/docs/blob/master/guides/installation/mamp.md

Please update it.
Please by an author who uses MAMP to be certain

**Comment by elkmod** [comment]
We're going to update the guide to using PHP8, Node14 and review the  rest of the guide with regard to executed commands and configuration.

**Comment by JoshuaBehrens** [comment]
Woop woop. Thank you :)

**Comment by sushmangupta** [comment]
@JoshuaBehrens , MAMP is deprecated now. Hence, closing this issue. 👍
