### ISSUE TITLE
Authorized state missing in diagrams

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/docs#569]
https://developer.shopware.com/docs/concepts/commerce/checkout-concept/orders is missing some states. As the plantuml files are missing from versioning I can't update it nicely. Can you please update it?

**Comment by Isengo1989** [comment]
@JoshuaBehrens @shyim We are using [Mermaid](https://mermaid.live/edit#pako:eNpVjk2Lg0AMhv9KyGkX6h_wUGh1txehhfbmeAgaO0M7H4yRUtT_vuN62c0p5Hne8E7Y-o4xx_7pX62mKHArlYM0h7rQ0QxiaWggy_bziQWsd_ye4fhx8jBoH4Jx98_NP64SFFO1agyijXssGyp-82fHM5R1RUF8aP6S28vP8FWbi07v_xMdOaW-657ynrKWIhQUG9yh5WjJdKn6tAYUimbLCvO0dtzT-BSFyi1JpVH89e1azCWOvMMxdCRcGrpHsttx-QG-cVWh) in the future for all UML diagrams to have a consistent view and versioning.

As for the payment transitions, it could be a little bit messy/huge. I thought about using the Froshtools State Machine Viewer. What's your thought on that?


![payment-state-transitions](https://github.com/shopware/docs/assets/8600299/f33d1926-d6ec-43b7-b01b-c82008b6f64d)

**Comment by JoshuaBehrens** [comment]
For this kind of graph there is likely some interactivity needed. So one could maybe click on a node and see the connections highlighted. But I see that this gets confusing :/ Unsure which tool is better for this. I work with neither

**Comment by Isengo1989** [comment]
WIP - https://github.com/shopware/docs/pull/1121

**Comment by sushmangupta** [comment]
The order state in the diagrams has been rectified to include any missing information. However, please note that the zoom effect on these diagrams is still a WIP. Given that the initial concern was specifically related to updating the diagrams, I consider this addressed; hence closing the ticket.
