### ISSUE TITLE
Please add the actual PUMLs to the docs

### ISSUE THREAD

**Issue by vardumper** [shopware/docs#590]
I am referring to https://github.com/shopware/docs/blob/master/concepts/commerce/checkout-concept/orders.md

Would it be possible that you also add the actual PlantUMLs to this repo, not just the images? 
If someone adds a state, modifies the order lifecycle, etc. it would be handy not to start from scratch but if one could document custom changes in a pre-made UML.

Much appreciated. Thank You!

**Comment by JoshuaBehrens** [comment]
UML diagrams are not their strengths https://github.com/shopware/docs/issues/250

**Comment by sushmangupta** [comment]
@vardumper , Sorry for the delayed response. Also, thanks for sharing your opinion. 
Here is the good news, we have recently started incorporating mermaid for rending UML diagrams. I am sure this would make your experience with our docs even better going forward. :)
