### ISSUE TITLE
Connection between mail type technical names and state changed events

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/docs#6]
I just stumbled upon the connection between the technical name of a mail type and the state machine states. Will there be an entry in the docs about it? This is super powerful although weird design decision.

@PaddyS 
@leichteckig 
@mitelg

**Comment by sushmangupta** [comment]
@JoshuaBehrens , is this still of interest?

**Comment by JoshuaBehrens** [comment]
As business_events have been changed to flows, events and actions this is likely resolved. It is less of a mystery given a task about new mails to new Shopware developers :)
