### ISSUE TITLE
Critera Instance with ids? 

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopware/docs#632]
On this page on line 48 is "new Criteria()" mentioned: 
docs/resources/references/core-reference/dal-reference/filters-reference.md

But Criteria needs an array of id's in the future.

**Comment by Christian-Rades** [comment]
Hi @Nico-Schaefer-2111,
The deprecation in the Criteria constructor forbids an empty array as a parameter in the future.
Calling the constructor without any parameters will stay okay.

```php
new Criteria([]) // deprecated
new Criteria() // still allowed
// expands to
new Criteria(null)
```
