### ISSUE TITLE
These docker instructions no longer work

### ISSUE THREAD

**Issue by ssirag** [shopware/docs#643]
I see these shopware install docs have been updated recently, with docker install supported.  However, the only place in the Shopware repos I can find the requisite yml files for the docker command to function (https://github.com/shopwareLabs/shopware-docker), the repo hasn't been maintained for 3 years and the commands no longer work.

Can you clarify where the source repo is that work with the commands referenced?

**Comment by elkmod** [comment]
Hi @ssirag - thank you for brining this up. We are planning an improvement for the docker setup instructions, as the one that you are referring to are outdated by now. 

For now, we recommend [shopware-docker](https://github.com/shyim/shopware-docker/wiki/Installation) for local development environments.

**Comment by elkmod** [comment]
Related: [DX-150](https://shopware.atlassian.net/browse/DX-150)

**Comment by sushmangupta** [comment]
@ssirag, thanks for raising the issue. The related ticket is resolved and docs are updated. Hence closing the issue.
