### ISSUE TITLE
The installation docs are out of date

### ISSUE THREAD

**Issue by mitelg** [shopware/docs#652]
The installation way documented [here](https://developer.shopware.com/docs/guides/installation/from-scratch#setting-up-shopware) is not up-to-date. 

It still has parts with `psh.phar` and the development template. Sames goes for the quick start in the [readme file](https://github.com/shopware/platform#quickstart--installation)

**Comment by Christian-Rades** [comment]
Related: [DX-150](https://shopware.atlassian.net/browse/DX-150)

**Comment by sushmangupta** [comment]
Thank you for reporting the issue @mitelg . The related ticket [DX-150](https://shopware.atlassian.net/browse/DX-150) has been resolved, hence closing the issue.
