### ISSUE TITLE
How to use filter within custom rules

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopware/docs#712]
Please explain how to use filter within custom rules. This is not mentioned on https://github.com/shopware/docs/tree/master/guides/plugins/plugins/framework/rule/add-custom-rules.md

**Comment by sushmangupta** [comment]
@Nico-Schaefer-2111 , can you brief a little more on what filters and what can be added as part of custom rules?

**Comment by Isengo1989** [comment]
@Nico-Schaefer-2111 is this still of interest? If no further information is given within the next 2 weeks, we will close the issue. Feel free to create a new one with more details :)

**Comment by sushmangupta** [comment]
Since there has been no recent response, we assume there is no further information needed. Hence closing this ticket. If you have any questions in the future, feel free to open a new ticket. Thank you for your understanding."
