### ISSUE TITLE
Make understandable instructions and examples

### ISSUE THREAD

**Issue by grzegorzgit** [shopware/docs#720]
Shopware documentation is very unclear and complicated. 

This page is an example howthe doc is written: https://developer.shopware.com/docs/guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities
To add one simple field to an entity you have to:
- create plugin (go to other page)
- create custom extension class
- make dependency injection (go to other page)
- learn about oneToOne association (go to other page)
- create ExampleExtensionDefinition (what is that? is it an official name? you don't mention)
- create new entity (go to other page)
- register field in DI container (I guess it is 'dependency injector', nice that you do this unclear abbrevations)
- create database table using database migration (go to other page)
- learn about repositories and writting data (go to other page)

All these only to add one field to a product. And the way it is explained is very disorderly.

**Comment by Isengo1989** [comment]
Since there has been no response for over a month, we will close this issue. Please feel free to answer the question above whenever. Your feedback is valuable to us and helps to improve your experience with the docs :+1:
