### ISSUE TITLE
Automated documentation linting

### ISSUE THREAD

**Issue by swsrmes** [shopware/docs#755]
Since there are many new, exciting changes happening within the Shopware documentation space, and many concrete processes being established therein, I see a prime opporunity for establishing automated jobs within the documentation PR flow.

An obvious facet is spellchecking, which could be achieved using Github actions [such as this](https://github.com/marketplace/actions/github-spellcheck-action). I [attempted this](https://github.com/ScottA38/shopware-docs/tree/WIP-add-spellcheck) previously, but I am currently stuck, with the issue persisting that pyspelling doesn't seem to understand the markdown correctly, despite a markdown extension being added/configured. Given it uses non-vanilla markdown syntax, it could be worth writing some customised regex filters for the extended markdown token set.

There is also a great opportunity to establish documentation linters, which will catch obvious and lexically concrete errors or issues, such as [heading casing](https://github.com/marketplace/actions/github-spellcheck-action) or flagging [date-time format](https://github.com/marketplace/actions/github-spellcheck-action).

In order to achieve such automated enforcing/linting of documentation lexical style rules, we could consider a configurable tools such as TextLint [](https://textlint.github.io/)

This could limit the number of mistakes reaching the review stage, and limit load on the reviewers of the docs.

**Comment by sushmangupta** [comment]
Thank you for the suggestion. We have noted and shall consider incorporating it.

**Comment by Isengo1989** [comment]
@swsrmes short update - we are currently looking into the options here and compare the given actions with other to use the best option for our docs :+1:
