### ISSUE TITLE
Wrong information in doc article

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopware/docs#786]
The following file includes the Information, that the css-Tag is available since Shopware 6.4.12.0 but it is only available since 6.4.13.0

guides/plugins/plugins/storefront/add-scss-variables.md

See here 
https://github.com/shopware/platform/commit/98c8ee6c2ef8646ad9d5a42d1cb036306e80181f

**Comment by sushmangupta** [comment]
Hi @Nico-Schaefer-2111,
Thanks for pointing that out. 
There was some discrepancy in our [changelog website](https://www.shopware.com/de/changelog/) which is now rectified and the necessary update has been made in the [doc article](https://developer.shopware.com/docs/guides/plugins/plugins/storefront/add-scss-variables).
