### ISSUE TITLE
Where can one finde JS-plugins from plugins installed via composer?

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopware/docs#822]
Tried to override a js plugin which is provided by another plugin. Therefore I followed the instructions on 
https://developer.shopware.com/docs/guides/plugins/plugins/storefront/override-existing-javascript 

But when i try to compile it just gives me a 'Module not found' error: 
Module not found: Error: Can't resolve 'src/plugin/moorl-form-builder-v2/moorl-form-builder-v2.plugin'

Do we have to use absolute path here ? 

Edit: the 3rd party plugin is installed via composer

**Comment by sushmangupta** [comment]
@Nico-Schaefer-2111 , hope this helps.  :)
