### ISSUE TITLE
Store API - No way to retrieve current active billing address? - Probably just missing in docs

### ISSUE THREAD

**Issue by AndreasA** [shopware/docs#835]
### PHP Version

8.1

### Shopware Version

6.4

### Expected behaviour

add active billing address to either cart response or context or customer of the store API.

### Actual behaviour

Context route does not provide any information for active billing address. the default address can be retrieved through the customer route but not the active billing address.

the shipping location is on the context and cart deliveries, so that is available, but I cannot see anything for the billing address. Though it probably would not hurt to also add the active shipping address with the customer route.

### How to reproduce

See above.

Or maybe I just don't know the correct API ?

**Comment by Isengo1989** [comment]
This should be fixed by now - please see [here](https://github.com/shopware/shopware/blob/trunk/changelog/release-6-5-6-0/2023-09-07-expose-active-billing-address-over-context-api.md)
