### ISSUE TITLE
Add Data to Storefront Page - Tutorial Issue

### ISSUE THREAD

**Issue by nikkoch** [shopware/docs#907]
I tried to implement it multiple times, googled for a week already and still I can't make it work via this tutorial: 
https://github.com/shopware/docs/blob/master/guides/plugins/plugins/storefront/add-data-to-storefront-page.md

I can't move on because of this error: 
"Too few arguments to function CustomFilter\Core\Content\Example\SalesChannel\ProductCountRoute::__construct(), 0 passed in /chroot/home/domain.de/html/vendor/shopware/core/Framework/DependencyInjection/CompilerPass/EntityCompilerPass.php on line 50 and exactly 1 expected"

This tutorial works well (I have finished it until caching), but it has a bit different structure and I was not able to glue it with a previous one:
https://github.com/shopware/docs/blob/master/guides/plugins/plugins/framework/store-api/add-store-api-route.md

How can we solve this? I see, that I'm not the only one struggling with the issue: 
https://forum.shopware.com/t/api-route-zu-erstellen-sehr-schwer-trotz-docu/96415/15

**Comment by sushmangupta** [comment]
@shopware/ct-storefront, What do you think about this?

**Comment by ssltg** [comment]
Hi @nikkoch 

thank you for bringing this up. We will take a look at it with this issue ticket: https://issues.shopware.com/issues/NEXT-26156

**Comment by ssltg** [comment]
Hi @nikkoch

we clarified (and fixed) the documentation in some points. You can take a look here https://github.com/shopware/docs/pull/962 and it would be great if you can give us feedback if the documentation is now more clear and working for you.
👍
