### ISSUE TITLE
Add Admin Search variables in "Set up Elasticsearch"-article

### ISSUE THREAD

**Issue by fholtgrefe-sw** [shopware/docs#935]
In Shopware 6.4.19.0, the "AND/OR Search in Admin" feature was released based on Elasticsearch Search. Therefore, please add the config variables in the "Set up Elasticsearch"-article:

```
ADMIN_OPENSEARCH_URL=YOUR OPEN SEARCH URL 
SHOPWARE_ADMIN_ES_ENABLED=1
SHOPWARE_ADMIN_ES_REFRESH_INDICES=1
SHOPWARE_ADMIN_ES_INDEX_PREFIX=sw-admin
```

Also the CLI Commands should be added: 
```
bin/console es:admin:index                                              
bin/console es:admin:reset                                              
bin/console es:admin:test    
```

Article: https://developer.shopware.com/docs/guides/hosting/infrastructure/elasticsearch/elasticsearch-setup

**Comment by sushmangupta** [comment]
Thanks for the hint. Created a ticket to add the info : https://shopware.atlassian.net/browse/DX-355
