### ISSUE TITLE
Just the file extension in config/packages

### ISSUE THREAD

**Issue by wolf128058** [shopware/docs#945]
https://github.com/shopware/docs/blob/c084fca586c6ea3d64de29c9b5bfc741962cd662/guides/hosting/performance/lock-store.md?plain=1#L9

All files in this directories end with yaml and not with yml.
I guess this one should be with an a, too.

**Comment by keulinho** [comment]
IIRC `.yaml` or `.yml` does not make any difference.

**Comment by JoshuaBehrens** [comment]
They are also both loaded the same as `\Shopware\Core\Kernel::CONFIG_EXTS` contains both extensions

https://github.com/shopware/platform/blob/024f418f4681fe9d712e95ec1a61f0349dcb4dc0/src/Core/Kernel.php#L27

https://github.com/shopware/platform/blob/024f418f4681fe9d712e95ec1a61f0349dcb4dc0/src/Core/Kernel.php#L243

**Comment by sushmangupta** [comment]
@wolf128058 , Thanks for the request. I hope you have been answered. Hence closing this issue 👍
