### ISSUE TITLE
Non-existent class referenced for Unit testing

### ISSUE THREAD

**Issue by lukdiekm** [shopware/docs#959]
Hi,

according to https://developer.shopware.com/docs/guides/plugins/plugins/testing/php-unit it should be possible to use a class called Shopware\Production\Kernel to use the production template for unit testing.

It seems as this class does not exist in 6.5.0.0:

```
PHPUnit 9.6.8 by Sebastian Bergmann and contributors.

Error in bootstrap script: RuntimeException:
Class "Shopware\Production\Kernel" doesn't exist or cannot be autoloaded. Check that the KERNEL_CLASS value in phpunit.xml matches the fully-qualified class name of your Kernel or override the Shopware\Core\Framework\Test\TestCaseBase\KernelLifecycleManager::createKernel() method.
...
```

Lukas

**Comment by sushmangupta** [comment]
@lukdiekm , thanks for raising the issue and sorry for the delayed response. An [internal ticket](https://shopware.atlassian.net/browse/NEXT-29625) is now created to address this issue.

**Comment by Isengo1989** [comment]
@lukdiekm there were some major changes in the docs, since the production template is no longer recommended as an installation method (use [FLEX](https://developer.shopware.com/docs/guides/installation/template) instead).

Please give it another go

**Comment by Isengo1989** [comment]
Since there has been no response for two weeks, I will close the issue as it seems it got resolved by the last comment / is not worked on by the creator anymore.

Thank you for bringing up the topic :+1:
